### ISSUE TITLE
JOSS Review: Community guidelines are missing

### ISSUE THREAD

**Issue by trappitsch** [silkemaes/MACE#11]
Please document community guidelines, see, e.g., the [JOSS reviewer isntructions here](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines).

**Comment by silkemaes** [comment]
I added these in the README and on the documentation website.

**Comment by trappitsch** [comment]
I see you set up a contact section. From the JOSS reviewer instructions:

> 
> There should be clear guidelines for third-parties wishing to:
>  - Contribute to the software 
>  - Report issues or problems with the software
>  - Seek support

Could you add a statement about contributions?

**Comment by silkemaes** [comment]
Hi @trappitsch, I added these statements to the readme.
