### ISSUE TITLE
JOSS Review: API Documentation

### ISSUE THREAD

**Issue by trappitsch** [silkemaes/MACE#12]
There doesn't seem to be any API documentation. Please provide an API documentation as required by JOSS, see, e.g., [here](https://joss.readthedocs.io/en/latest/review_criteria.html#api-documentation)

**Comment by silkemaes** [comment]
I documented all functions in the scripts. Do I need to document this in another way?

**Comment by trappitsch** [comment]
Ah, I see. Sorry, I was mostly checking the documentation. I think this would be fine as there are no specifics defined on where it should be documented, and in the source code does make sense. Thanks!
