### ISSUE TITLE
JOSS Review: Issues with training the MACE model using the annotated notebook

### ISSUE THREAD

**Issue by richings** [silkemaes/MACE#14]
Hi @silkemaes  

I have tried to run the annotated notebook for training a MACE model that you provide in the Documentation here: 

https://mace-code.readthedocs.io/en/latest/use/routine.html 

(This is the one that's based on the `routine.py` script). However, I had a couple of problems with running this notebook that meant I was unable to train the model. 

Firstly, when I import the dataset using: 

`import src.mace.CSE_0D.dataset  as ds`

It gives me an error message that it can't find `MACE/data/rate16.specs` 

I can see the `rate16.specs` file is in the parent `MACE/` directory, so I created a new sub-directory `MACE/data` and put it in there. Is this correct? That did at least avoid the file not found error, so it was able to run. Would it be worth moving this file into the "data" directory in the repository too, to make it easier to find when we run the notebook? Also, the `rate16.specs` file that I got from the repository (on the JOSS branch) is empty, is this correct? 

I then got as far as loading the train, validation and test datasets, but when I try to load these using the `ds.get_data` function it gives me the following error: 

`FileNotFoundError: /STER/silkem/MACE/data/paths_data_C.txt not found.`

There are a couple of issues here: 

- It looks like it is searching for the file in the MACE directory located in `/STER/silkem/MACE`. I tried to update the paths in the Jupyter Notebook that you gave in the documentation so that the paths point to the correct directories on my machine, but I think there are some places in the code where it is still hard-coded to the path on your machine? E.g. in `src/mace/CSE_0D/dataset.py` on line 85 it has the following: 

`loc = '/STER/silkem/MACE/'`

I think this is why it is looking for the file in the wrong directory? 

- Secondly, it is looking for a file called `paths_data_C.txt`, but I'm not sure where this file is, I couldn't see it in the repository? Is there another step that I need to do beforehand to create or set up this file? Sorry if I missed it!

**Comment by silkemaes** [comment]
Hi @richings,

You were correct to notice some files were missing or empty by accident. These issues should be fixed now.

I added a notebook version of the routine-script, which is similar to the notebook found on the documentation page. Because the documentation pages (and notebooks there) live on the main branch. 

Hopefully now you are able to run the routine notebook without errors.

**Comment by richings** [comment]
Hi @silkemaes  

Thanks for the updates! I have tried running the routine.ipynb Jupyter Notebook that you have added on the JOSS branch. This has fixed the errors that I was finding earlier, and I can now run it further than I managed before. However, I am struggling to reproduce the same plots that you have in the notebook. 

So I created a copy of the notebook from the repository and I restarted the kernel and cleared all outputs. I then tried to run through the notebook, but using the same pre-trained model that you provide, so I skip the "Set up the model" cell. I get to Stage 1, where it does the initial training with unscaled losses. It appears that it does train for 5 epochs, as you have in your copy of the notebook. However, the plot that it produces looks very different. When I do it, the plot only shows points at epoch 0.00, and the x-axis only extends from -0.05 to +0.05. But in your notebook, the plot that it produces after Stage 1 covers epochs of 0 to 13. I have attached a copy of the plot that I get when I run it below. 

![routine_stage1_plot](https://github.com/user-attachments/assets/c8de2b67-424a-46de-8a14-bd673cac7ddc)

Am I doing something wrong here? 

I then continued with Stage 2, where it continues the training with re-scaled losses. It trains for epochs 6 to 15, which is also the same as you have in your notebook. And the two plots that it produces here are closer to what you have, although the range on the x-axis is again a bit different. On my plots the first one covers epochs 0-5 and the second one 0-14 (which I think makes sense given how many epochs it has trained for), but on your notebook they cover epochs 0 to 30 and 0 to 40 respectively. 

Btw in the Stage 2 plots, the losses suddenly jump (after epoch 4 in my plots, and after epochs 14-17 in your plots). Is this jump to be expected? Am I right in saying this is just because the losses are re-scaled after that epoch? 

I was then able to save the model no problem. However, when I then tried the Testing the Model section, the cell under Performing the tests seems to take a long time. I gave it a few minutes but it didn't seem to make much progress. Is this expected? Although I noticed that when I run this cell it says "Selected Paths: 1000", but in your copy of the notebook it says "Selected Paths: 4" and "Selected test paths: 100", maybe this is why it is taking a lot longer when I run it?

**Comment by silkemaes** [comment]
Hi @richings,

There were indeed still some issues with the routine notebook and the input files.

- Normally the plotting of the losses should work. There were general issues with plotting in python notebooks, that is always shows the plot, even without the ```plt.show()``` command. I normally made sure that now only the plots I aim to show are visible.
- The plotting should now work for stage 1 as well as stage 2.
- It is correct that the testing of the models didn't work properly, I found the hard coded number ```100``` somewhere, and removed this. I also added a bit more data: 13 samples in total, of which 10 for training + validating (with 70%-30% ratio) and 3 for testing. I of course know this is way too little data to properly train anything in machine learning, but here the data is just there to show the code works.

I hope with this you can continue.

**Comment by richings** [comment]
Hi @silkemaes 

Great, thanks! That has fixed the errors I was finding, and I am now able to run the routine.ipynb notebook no problem and I can reproduce your results. 

I then tried to run the load&test.ipynb notebook in the repository, this is the same as the one provided in the documentation here: 

https://mace-code.readthedocs.io/en/latest/example/load%26test.html 

I can run the "Loading the model" section no problem, and it produces the same plot that you had. However, when I then run the Testing the model section, it creates the first group of plots OK but part way through it gives an error: 

ValueError: Unrecognized marker style 'none'

It looks like this is coming from matplotlib, if I look through the traceback I think it originates from line 75 of MACE/src/mace/CSE_0D/plotting.py where it has: 

line, = ax1.plot(r,n_hat[:,idx], ls =ls, marker = marker, label = spec, ms = ms,  lw = lw)

It sounds like it might be trying to set the marker style as a string 'none' rather than as a None type python object?

**Comment by silkemaes** [comment]
Hi @richings,

I adjusted the marking type in the plotting script, though it is strange it throws an error since 'none' as a string should work as marker.

Anyway, it doesn't matter too much which marker is used there.

Hopefully you can proceed.

Thanks!

**Comment by richings** [comment]
Hi @silkemaes, 

Great, many thanks! That has fixed the problem I was having, I am now able to run both of the annotated Jupyter Notebooks, and I can reproduce your results. 

I will mark this issue as resolved.
