### ISSUE TITLE
Cannot run `routine.py` or `routine.ipynb` successfully

### ISSUE THREAD

**Issue by trappitsch** [silkemaes/MACE#15]
I'm having issues when running the example case form the repo:

- `routine.ipynb` fails in stage 1, cell `[13]` when training the model:
  ```
  FileNotFoundError: [Errno 2] No such file or directory: './data/train/20211014_gridC_Mdot1e-7_v15_T_eps_model_2022-12-28h15-08-21/input.txt'
  ```
  Looking into the folder, it seems as if the model was renamed.
- Using `routine.py` already fails as the folders in the `path` that are setup are not created. Please double check, this seems to be different in the notebook.

**Comment by silkemaes** [comment]
Hi @trappitsch,
- The issue with loading the input file for the training data should be fixed now.
- It is true that yesterday I added the notebook "routine.ipynb", which is based on the python script but not fully compatible. I'll fix this still.

Hopefully currently you are able to run the routine notebook fully.

**Comment by trappitsch** [comment]
I'll wait for looking at the notebook then. Checking out your push right now: The folder issue is solved in `routine.py`, but I get this error:

```
Traceback (most recent call last):
  File "/home/reto/Documents/reviews/2024_joss_Maes/MACE/routine.py", line 164, in <module>
    err_test, err_evol, step_time, evol_time = test.test_model(model,testpath, meta, printing = False)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reto/Documents/reviews/2024_joss_Maes/MACE/src/mace/test.py", line 147, in test_model
    model1D, input, info = ds.get_test_data(testpath, meta, inpackage = inpackage, train = train)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reto/Documents/reviews/2024_joss_Maes/MACE/src/mace/CSE_0D/dataset.py", line 241, in get_test_data
    mod = CSEmod(testpath, inpackage, train)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reto/Documents/reviews/2024_joss_Maes/MACE/src/mace/CSE_0D/dataset.py", line 345, in __init__
    self.Rstar, self.Tstar, self.Mdot, self.v, self.eps, self.rtol, self.atol = read_input_1Dmodel(inp_path)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reto/Documents/reviews/2024_joss_Maes/MACE/src/mace/CSE_0D/dataset.py", line 472, in read_input_1Dmodel
    with open(file_name, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/STER/silkem/CSEchem/_inputChemistry_model_2022-12-23h14-08-04.txt'
```

Seems like there is still a hardcoded path that is used.

**Comment by silkemaes** [comment]
Hi @trappitsch, I now adjusted the script ```routine.py``` to be compatible with the notebook. Normally it should work now. Also an updated version of the notebook is available.

**Comment by trappitsch** [comment]
Thanks, both are working now!
