### ISSUE TITLE
JOSS Review: Problem with installation / missing installation documentation

### ISSUE THREAD

**Issue by trappitsch** [silkemaes/MACE#8]
Trying to install MACE I encountered some issues below:

- There is no section on installation in the docs or in the repo readme. This should be added!
  - Currently, it seems as if `MACE` will not be available on `pypi`, are you planning on changing this?
  - There is a package named `MACE` on `pypi`. Just to avoid user confusion, please state in the installation section that this is not the same as your package.
  - Please provide installation instructions from GitHub: Install as a package, clone and install? What is possible / what is recommended?
- I had some issues with dependency resolving. The culprit is `numba`, a wonderful package. However, this agrees well with my experience, to get `numba` to run reproducebly, it is crucial to pin the required dependencies according to the the [numba requirements](https://numba.readthedocs.io/en/stable/user/installing.html#numba-support-info):
  - `requires-python = ">=3.9,<3.13"` (python `3.8` will be EOL in a couple of months!)
  - `numba ~= 0.60.0`  (this one is a very tricky dependency that I would highly recommend to pin)
  - `numpy < 2.27`

There is definitely overlap of these issues with #7, however, I put them into a new issue as the scope is slightly different. Hope that's okay.

**Comment by trappitsch** [comment]
In addition to above issue, upon first import after installation using the provided `pyproject.toml` file (with the discussed changes), the following packages seem to be missing and thus should be added to the `pyproject.toml` file:

- scipy
- torchode

**Comment by silkemaes** [comment]
Hi @trappitsch,

First of all thank you for reviewing, and sorry for the late response! I don't know if it was clear, but the aim was for the JOSS reviewers to review the code in the branch JOSS.

- MACE is indeed not available on ```pypi```, and the existing mace package is not ours. I added this information to the readme, as well as instructions on how to get started with MACE.
- I removed the numba requirement from the toml-file, this was something remaining from early development and not used in the end. I also added ```scipy``` and ```torchode``` to the toml-file.

**Comment by trappitsch** [comment]
Hi @silkemaes

Thanks for the info, I switched over to the JOSS branch, must have missed this somehow. 
I could now install the dependencies with the updated version without any problems, so that all seems to make sense. One slight inconsistency still exists in the `pyproject.toml` file: You say MACE `requires-python = ">=3.7"`, however, you pin `"torch>=2.0.0"`, which in itself requires at least python `>=3.8`. With some dependency managers, this will throw an error, however, the standard `pip` installation seems to be fine with it as long as I use python `>=3.8`.
