### ISSUE TITLE
JOSS Review: Import errors when loading examples

### ISSUE THREAD

**Issue by trappitsch** [silkemaes/MACE#9]
Trying to run the [Training a MACE model](https://mace-code.readthedocs.io/en/latest/example/run.html) on my machine locally, I already have issues with importing MACE. I am getting many path errors, which I think are due to the fact that imports inside the MACE modules seem to relative to `src`. I installed `mace` into my virtual environment, so it should be available as `import mace` (and is). Looking into the source files however, e.g., `src/mace/loss.py`, import statements are (see, e.g,. line 14): `import src.mace.utils as utils`. This naturally leads to issues when mace is installed as a package, which might be wrong?

I think this will be clarified with answers to issue #8, however, this seems to be where I'm stuck at the moment.

**Comment by silkemaes** [comment]
For me it works on my machine with the modules relative to ```scr```, when installing MACE as a package locally.

I'm not completely sure how else I can load scripts from the source directory into my scripts. Do you maybe have a suggestion on how this is usually done?

**Comment by trappitsch** [comment]
With the new instructions, the import errors are gone, thanks for clarifying.
